name: Feature Request
description: Suggest a new feature
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: Problem
      description: What problem would this solve?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed solution
      description: How should this work?
  - type: textarea
    attributes:
      label: Alternatives considered
      description: Any other approaches you considered?
